// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kudblitjlevsjxlrzxlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZGJsaXRqbGV2c2p4bHJ6eGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1OTA5MzksImV4cCI6MjA0OTE2NjkzOX0.cybpMoVoSqLEYM39vSfUcGh0Ru2ABfWV7E8n-z22vs4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);